apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  namespace: web
spec:
  type: NodePort
  selector:
    app: employees-deploy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
